In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array([1,2,3,'Sai',2+10j])     # It upcasts (typecast) the data to highest order of data in the list

array(['1', '2', '3', 'Sai', '(2+10j)'], dtype='<U64')

In [6]:
np.array([1,4,5.6,6.0])

array([1. , 4. , 5.6, 6. ])

In [8]:
np.array([[1,3], [3,4], [6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [9]:
np.array([[1,3], [3,4], [6,7,8]])

C:\Users\Sai\AppData\Local\Temp\ipykernel_3784\1024472721.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3], [3,4], [6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [11]:
np.array([[[1,3], [3,4]], [[1,3], [3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [14]:
np.array([1,2,3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [15]:
np.array([1,2,3], dtype= complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [16]:
np.array([(1,2), (3,4)])

array([[1, 2],
       [3, 4]])

In [18]:
arr = np.array([(1,2), (3,4)], dtype=[('a' , '<i2'), ('b' , '<i8')])

In [19]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [20]:
arr[0]

(1, 2)

In [21]:
arr[0][0]

1

In [23]:
type(arr[0][0])      # i2 represents 16 bit

numpy.int16

In [24]:
type(arr[0][1])       #i8 represents 64 bit

numpy.int64

In [30]:
arr = np.array([(1,2), (3,4)], dtype=[('a' , '<i4'), ('b' , '<i8')])

In [31]:
type(arr[0][0])       #i4 represents 32 bit

numpy.int32

In [32]:
arr = np.array([[1,3], [5,6]])

In [33]:
arr

array([[1, 3],
       [5, 6]])

In [34]:
type(arr[0])

numpy.ndarray

In [35]:
type(arr[0][1])

numpy.int32

In [36]:
np.mat(arr)

matrix([[1, 3],
        [5, 6]])

In [44]:
mat = np.matrix(arr)

In [46]:
mat

matrix([[1, 3],
        [5, 6]])

In [38]:
l = [3,4,5,6,7,8]        # List is not in any form of array, So it tries to do conversion

In [42]:
np.array(l)

array([3, 4, 5, 6, 7, 8])

In [39]:
np.asarray(l)

array([3, 4, 5, 6, 7, 8])

In [40]:
np.asanyarray(l)

array([3, 4, 5, 6, 7, 8])

In [45]:
np.asanyarray(mat)       # Matrix is a subset of array, So it doesn't try to co conversion

matrix([[1, 3],
        [5, 6]])

In [48]:
issubclass(np.matrix, np.ndarray)     # ndarray is the parent class

True

In [49]:
issubclass(np.ndarray, np.matrix)     # matrix is the sub class

False

In [50]:
arr

array([[1, 3],
       [5, 6]])

In [51]:
a = arr

In [52]:
b = np.copy(arr)

In [54]:
arr[0][0] = 67

In [55]:
arr

array([[67,  3],
       [ 5,  6]])

In [56]:
a          # Shallow Copy

array([[67,  3],
       [ 5,  6]])

In [57]:
b         # Deep Copy

array([[1, 3],
       [5, 6]])

In [59]:
arr[0:10]

array([[67,  3],
       [ 5,  6]])

In [61]:
arr[-1]

array([5, 6])

In [62]:
for i in arr:
    print(i)

[67  3]
[5 6]


In [63]:
np.fromfunction(lambda i,j : i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [64]:
type(np.fromfunction(lambda i,j : i==j, (4,4)))

numpy.ndarray

In [66]:
np.fromfunction(lambda i,j:i**j, (3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [67]:
np.fromfunction(lambda i,j:i/j, (3,3))    # In numpy zeroDivisionError is not there, 'inf' keyword is there

C:\Users\Sai\AppData\Local\Temp\ipykernel_3784\106629710.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j:i/j, (3,3))
C:\Users\Sai\AppData\Local\Temp\ipykernel_3784\106629710.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j:i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [68]:
1/0

ZeroDivisionError: division by zero

In [69]:
[x*x for x in range(5)]

[0, 1, 4, 9, 16]

In [88]:
gen = (x*x for x in range(5))

In [89]:
gen
for i in gen:
    print(i)

0
1
4
9
16


In [74]:
def test(x):
    yield x

In [72]:
test(5)

<generator object test at 0x000001FE9EB10C80>

In [85]:
np.fromiter(gen, dtype=int)

array([ 0,  1,  4,  9, 16])

In [86]:
np.fromiter(range(5), dtype=int)

array([0, 1, 2, 3, 4])

In [91]:
np.fromstring('1,3,6,5,5', sep=',', dtype= int)

array([1, 3, 6, 5, 5])

In [95]:
np.fromstring("456 854 632 123 4545", sep=' ', dtype= complex)

array([ 456.+0.j,  854.+0.j,  632.+0.j,  123.+0.j, 4545.+0.j])

In [96]:
l = [3,4,5,6]

In [98]:
arr = np.array(l)

In [104]:
arr1 = np.array([[1,2,3,4], [2,3,4,5], [3,4,5,6]])

In [100]:
arr1

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]]

In [101]:
type(arr)

numpy.ndarray

In [102]:
arr.ndim

1

In [105]:
arr1.ndim

2

In [107]:
arr1.size

12

In [108]:
arr1.shape

(3, 4)

In [110]:
arr1.dtype

dtype('int32')

In [111]:
arr

array([3, 4, 5, 6])

In [112]:
arr.size

4

In [114]:
arr.ndim

1

In [115]:
arr.shape

(4,)

In [118]:
arr2 = np.array([[[1,2,3,4], [4,5,6,7]], [[1,2,3,4], [4,5,6,7]]])

In [119]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [120]:
arr2.size

16

In [121]:
arr2.shape

(2, 2, 4)

In [122]:
arr2.ndim

3

In [125]:
arr4 = np.array([[[[1,2,3,4], [4,5,6,7]], [[1,2,3,4], [4,5,6,7]], [[1,2,3,4], [4,5,6,7]], [[1,2,3,4], [4,5,6,7]]]])

In [126]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [127]:
arr4.shape

(1, 4, 2, 4)

In [130]:
list(range(5))

[0, 1, 2, 3, 4]

In [131]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [132]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [133]:
np.arange(6.6, 9, .3)       # in floating point number it does not include the upper bound

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [134]:
np.arange(6.6, 9, -.3)

array([], dtype=float64)

In [135]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [136]:
np.linspace(3,8)   # bydefault 50 data set

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [137]:
np.linspace(1,9)       # returns evenly spaced data in the range

array([1.        , 1.16326531, 1.32653061, 1.48979592, 1.65306122,
       1.81632653, 1.97959184, 2.14285714, 2.30612245, 2.46938776,
       2.63265306, 2.79591837, 2.95918367, 3.12244898, 3.28571429,
       3.44897959, 3.6122449 , 3.7755102 , 3.93877551, 4.10204082,
       4.26530612, 4.42857143, 4.59183673, 4.75510204, 4.91836735,
       5.08163265, 5.24489796, 5.40816327, 5.57142857, 5.73469388,
       5.89795918, 6.06122449, 6.2244898 , 6.3877551 , 6.55102041,
       6.71428571, 6.87755102, 7.04081633, 7.20408163, 7.36734694,
       7.53061224, 7.69387755, 7.85714286, 8.02040816, 8.18367347,
       8.34693878, 8.51020408, 8.67346939, 8.83673469, 9.        ])

In [138]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [139]:
np.linspace(.3, .5, 5)

array([0.3 , 0.35, 0.4 , 0.45, 0.5 ])

In [140]:
np.linspace(2, 8, 4)

array([2., 4., 6., 8.])

In [141]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [143]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [144]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [145]:
np.zeros((2,5,4,1))

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [146]:
np.ones(4)

array([1., 1., 1., 1.])

In [149]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [150]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [151]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [153]:
np.empty((3,4))

array([[1.08351554e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.06099790e-312, 5.99409525e-066, 8.24598231e-071,
        1.90292921e+185],
       [1.40107949e-076, 3.56716214e-057, 6.52894621e-042,
        4.11998539e-033]])

In [154]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [155]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [157]:
np.linspace(2,4,4, endpoint=False, axis=0)

array([2. , 2.5, 3. , 3.5])

In [158]:
np.linspace(2,4,4, endpoint=False, axis=1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [160]:
np.linspace([1,6],4, endpoint=False, axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [161]:
np.linspace([1,6],4, endpoint=False, axis=0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [162]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [163]:
np.logspace([2,3], 4, axis=1)

array([[  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
          145.63484775,   159.98587196,   175.75106249,   193.06977289,
          212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
          308.88435965,   339.32217719,   372.75937203,   409.49150624,
          449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
          655.12855686,   719.685673  ,   790.60432109,   868.51137375,
          954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
         1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
         2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
         2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
         4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
         6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
         9102.98177992, 10000.        ],
       [ 1000.        ,  1048.11313415,  1098.54114199,  1151.39539933,
         1206.79264064,

In [164]:
np.logspace([2],[3], axis=1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [165]:
np.logspace([2],[3], axis=0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [169]:
d = np.linspace(4,7,40)

In [170]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [171]:
d.ndim

1

In [172]:
d.shape

(40,)

In [173]:
d.size

40

In [174]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [175]:
d.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [176]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [181]:
d.reshape(1,2,1,20)

array([[[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
          4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
          4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
          5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

        [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
          5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
          6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
          6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]]])

In [182]:
d.reshape(3,1,2,20)

ValueError: cannot reshape array of size 40 into shape (3,1,2,20)

In [183]:
np.random.rand(3)

array([0.93799448, 0.4092487 , 0.83856542])

In [184]:
np.random.randn(5)

array([ 0.75661029,  0.72012345,  3.32376249, -0.69763347, -1.08105068])

In [185]:
np.random.randn(2,3)

array([[ 2.20478716, -1.24475539, -0.35804633],
       [ 0.16008416,  1.44106694,  0.97516088]])

In [186]:
np.random.randn(2,2,3)

array([[[ 2.25227515, -0.97780431,  1.96059778],
        [ 0.72653666,  1.48695307, -0.61535623]],

       [[ 0.88851593,  0.59704026, -1.44560889],
        [-1.3287407 , -0.46450076, -0.82350116]]])

In [191]:
np.random.randint(5,60, (4,4))

array([[10, 52, 22, 30],
       [15, 19, 50, 44],
       [41, 52,  9, 59],
       [29, 51, 46, 21]])

In [192]:
arr = np.random.randint(3,9, (3,3))

In [193]:
arr

array([[3, 7, 3],
       [4, 6, 3],
       [7, 4, 8]])

In [194]:
arr.reshape(1,9)

array([[3, 7, 3, 4, 6, 3, 7, 4, 8]])

In [195]:
arr.reshape(9,1)

array([[3],
       [7],
       [3],
       [4],
       [6],
       [3],
       [7],
       [4],
       [8]])

In [196]:
arr.reshape(1,1,9)

array([[[3, 7, 3, 4, 6, 3, 7, 4, 8]]])

In [197]:
arr.reshape(3,3,1)

array([[[3],
        [7],
        [3]],

       [[4],
        [6],
        [3]],

       [[7],
        [4],
        [8]]])

In [198]:
arr.reshape(3,-1)

array([[3, 7, 3],
       [4, 6, 3],
       [7, 4, 8]])

In [199]:
arr.reshape(1, -1)

array([[3, 7, 3, 4, 6, 3, 7, 4, 8]])

In [200]:
arr.reshape(1, -1525455)

array([[3, 7, 3, 4, 6, 3, 7, 4, 8]])

In [201]:
arr.max()

8

In [206]:
arr.reshape(1, 1)

ValueError: cannot reshape array of size 9 into shape (1,1)

In [207]:
arr.reshape(1,9, -1)

array([[[3],
        [7],
        [3],
        [4],
        [6],
        [3],
        [7],
        [4],
        [8]]])

In [208]:
arr.min()

3

In [211]:
arr = np.random.randint(4,100, (5,5))

In [212]:
arr

array([[25, 32, 90, 82, 17],
       [10, 94, 75, 77, 40],
       [94, 72, 15, 79, 48],
       [11, 14, 30, 66, 57],
       [81, 23, 47, 37, 97]])

In [213]:
arr[3:, 3:]

array([[66, 57],
       [37, 97]])

In [214]:
arr[:,[1,3]]

array([[32, 82],
       [94, 77],
       [72, 79],
       [14, 66],
       [23, 37]])

In [215]:
arr

array([[25, 32, 90, 82, 17],
       [10, 94, 75, 77, 40],
       [94, 72, 15, 79, 48],
       [11, 14, 30, 66, 57],
       [81, 23, 47, 37, 97]])

In [217]:
arr > 50

array([[False, False,  True,  True, False],
       [False,  True,  True,  True, False],
       [ True,  True, False,  True, False],
       [False, False, False,  True,  True],
       [ True, False, False, False,  True]])

In [218]:
arr[arr > 50]

array([90, 82, 94, 75, 77, 94, 72, 79, 66, 57, 81, 97])

In [219]:
arr > 50

array([[False, False,  True,  True, False],
       [False,  True,  True,  True, False],
       [ True,  True, False,  True, False],
       [False, False, False,  True,  True],
       [ True, False, False, False,  True]])

In [221]:
arr

array([[25, 32, 90, 82, 17],
       [10, 94, 75, 77, 40],
       [94, 72, 15, 79, 48],
       [11, 14, 30, 66, 57],
       [81, 23, 47, 37, 97]])

In [220]:
arr * arr

array([[ 625, 1024, 8100, 6724,  289],
       [ 100, 8836, 5625, 5929, 1600],
       [8836, 5184,  225, 6241, 2304],
       [ 121,  196,  900, 4356, 3249],
       [6561,  529, 2209, 1369, 9409]])

In [233]:
arr1 = np.random.randint(2,4,(3,3))

In [232]:
arr2 = np.random.randint(2,4,(3,3))

In [223]:
arr1

array([[3, 2, 3],
       [2, 2, 3],
       [2, 2, 2]])

In [225]:
arr2

array([[3, 3, 2],
       [3, 2, 3],
       [3, 3, 2]])

In [226]:
arr1 * arr2

array([[9, 6, 6],
       [6, 4, 9],
       [6, 6, 4]])

In [228]:
arr3 = np.random.randint(2,4,(3,2))

In [229]:
arr3

array([[3, 3],
       [2, 2],
       [2, 2]])

In [230]:
arr1 * arr3

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [234]:
arr1@arr2

array([[16, 18, 19],
       [14, 16, 16],
       [18, 21, 21]])

In [235]:
arr/0

C:\Users\Sai\AppData\Local\Temp\ipykernel_3784\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [236]:
arr**2

array([[ 625, 1024, 8100, 6724,  289],
       [ 100, 8836, 5625, 5929, 1600],
       [8836, 5184,  225, 6241, 2304],
       [ 121,  196,  900, 4356, 3249],
       [6561,  529, 2209, 1369, 9409]], dtype=int32)

In [239]:
arr = np.zeros((3,4))

In [240]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [241]:
a = np.array([1,2,3,4])

In [242]:
a

array([1, 2, 3, 4])

In [243]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [244]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [245]:
b = np.array([1,2,3])

In [246]:
arr + b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [252]:
c = np.array([[5,6,7]])

In [248]:
c

array([5, 6, 7])

In [249]:
c.reshape(3,1)

array([[5],
       [6],
       [7]])

In [250]:
c.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [253]:
c.T

array([[5],
       [6],
       [7]])

In [254]:
c.T +arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [255]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [258]:
arr = np.random.rand(5,4)

In [259]:
arr

array([[0.74782114, 0.53970343, 0.24784354, 0.31677399],
       [0.30605289, 0.05593822, 0.67516467, 0.23351789],
       [0.79226434, 0.65037353, 0.49856701, 0.49713628],
       [0.77858946, 0.28870353, 0.28724057, 0.30129678],
       [0.6469934 , 0.49037439, 0.99840948, 0.86322979]])

In [260]:
np.sqrt(arr)

array([[0.86476652, 0.7346451 , 0.49783887, 0.56282678],
       [0.55322048, 0.23651263, 0.82168404, 0.48323689],
       [0.89009232, 0.8064574 , 0.70609278, 0.70507891],
       [0.88237716, 0.53731139, 0.53594829, 0.54890508],
       [0.804359  , 0.70026737, 0.99920442, 0.9291016 ]])

In [261]:
np.exp(arr)

array([[2.11239239, 1.71549802, 1.28125945, 1.37269229],
       [1.35805414, 1.05753235, 1.96435641, 1.26303542],
       [2.20839132, 1.91625648, 1.64636036, 1.64400654],
       [2.17839738, 1.33469597, 1.3327448 , 1.35161042],
       [1.90979021, 1.63292746, 2.71396178, 2.37080555]])

In [262]:
np.log10(arr)

array([[-1.26202261e-01, -2.67844824e-01, -6.05822395e-01,
        -4.99250488e-01],
       [-5.14203508e-01, -1.25229132e+00, -1.70590293e-01,
        -6.31679840e-01],
       [-1.01129891e-01, -1.86837141e-01, -3.02276462e-01,
        -3.03524546e-01],
       [-1.08691481e-01, -5.39547904e-01, -5.41754214e-01,
        -5.21005504e-01],
       [-1.89100150e-01, -3.09472218e-01, -6.91304318e-04,
        -6.38735795e-02]])

In [264]:
arr1 = np.random.randint(2,5, (5,5))

In [265]:
arr1

array([[2, 3, 2, 4, 3],
       [2, 2, 3, 4, 4],
       [2, 3, 3, 3, 3],
       [2, 2, 4, 3, 2],
       [3, 2, 4, 2, 3]])

In [266]:
np.log2(arr1)

array([[1.       , 1.5849625, 1.       , 2.       , 1.5849625],
       [1.       , 1.       , 1.5849625, 2.       , 2.       ],
       [1.       , 1.5849625, 1.5849625, 1.5849625, 1.5849625],
       [1.       , 1.       , 2.       , 1.5849625, 1.       ],
       [1.5849625, 1.       , 2.       , 1.       , 1.5849625]])

In [267]:
np.log10(arr1) 

array([[0.30103   , 0.47712125, 0.30103   , 0.60205999, 0.47712125],
       [0.30103   , 0.30103   , 0.47712125, 0.60205999, 0.60205999],
       [0.30103   , 0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.30103   , 0.30103   , 0.60205999, 0.47712125, 0.30103   ],
       [0.47712125, 0.30103   , 0.60205999, 0.30103   , 0.47712125]])

In [268]:
np.random.rand(2,4)

array([[0.05065674, 0.19670103, 0.71974081, 0.79536621],
       [0.72815305, 0.84417171, 0.64572677, 0.98066771]])

In [271]:
np.random.seed(30)        # to get random same exact same as someone else then use 'seed'
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])